In [1]:
import numpy as np
from sympy import python

In [2]:

arr = np.arange(1, 21)
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
indices = np.where(arr > 10)
print("Indices of elements > 10:", indices)



Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


In [3]:




arr2d = np.arange(1, 17).reshape(4, 4)
print("2D Array:\n", arr2d)
print("Transpose:\n", arr2d.T)
print("Row-wise Sum:", np.sum(arr2d, axis=1))
print("Column-wise Sum:", np.sum(arr2d, axis=0))



2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise Sum: [10 26 42 58]
Column-wise Sum: [28 32 36 40]


In [4]:

A = np.random.randint(1, 21, (3, 3))
B = np.random.randint(1, 21, (3, 3))
print("Array A:\n", A)
print("Array B:\n", B)
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Multiplication:\n", A * B)
print("Dot Product:\n", np.dot(A, B))


Array A:
 [[ 7 14  4]
 [16  3 15]
 [ 7 19 10]]
Array B:
 [[ 9 16  4]
 [ 3  5  1]
 [11 12 17]]
Addition:
 [[16 30  8]
 [19  8 16]
 [18 31 27]]
Subtraction:
 [[-2 -2  0]
 [13 -2 14]
 [-4  7 -7]]
Multiplication:
 [[ 63 224  16]
 [ 48  15  15]
 [ 77 228 170]]
Dot Product:
 [[149 230 110]
 [318 451 322]
 [230 327 217]]


In [5]:

arr1d = np.arange(1, 13)
arr2d_reshaped = arr1d.reshape(3, 4)
print("Reshaped 3x4 Array:\n", arr2d_reshaped)
print("Sliced Array:\n", arr2d_reshaped[:2, -2:])


Reshaped 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced Array:
 [[3 4]
 [7 8]]
